"""Update settings schema.

Revision ID: d2ffb83fba22
Revises: 06b81e536ae8
Create Date: 2024-04-16 10:47:38.930033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ffb83fba22'
down_revision = '06b81e536ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openaiModel', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('openaiMaxTokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bertScoreSamplingNr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gEvalSamplingNr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('gEvalSamplingNr')
        batch_op.drop_column('bertScoreSamplingNr')
        batch_op.drop_column('openaiMaxTokens')
        batch_op.drop_column('openaiModel')

    # ### end Alembic commands ###
